import Head from 'next/head';
import Details from '~/layouts/Details';
import TopLayout from '~/layouts/TopLayout';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <TopLayout>
                <Details />
            </TopLayout>
        </>
    );
}
